version: '3'

services:
  executions:
    image: wsumfest/execution-feed:v1
    container_name: executions
    networks:
      - internal
    depends_on:
      - nats
  sports:
    image: wsumfest/sport-feed:v1
    container_name: sports
    networks:
      - internal
    depends_on:
      - nats
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - 4222:4222
    networks:
      internal:
        aliases:
          - host.docker.internal
  postgres:
    build:
      context: ./
      dockerfile: postgres/Dockerfile     
    image: postgres:13.1-alpine
    container_name: postgres
    ports:
     - 5432:5432
    networks:
      internal:
        aliases:
          - pg.docker.internal
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      POSTGRES_PASSWORD: 1qaz2wsx
      POSTGRES_DB: st-chat
      POSTGRES_USER: st-chat
      POSTGRES_HOST: pg.docker.internal
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server 
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      internal:
        aliases:
          - redis.docker.internal
networks:
  internal:
    driver: bridge
volumes:
  pg_data:
  redis:
