# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x65xecution.proto\"y\n\texecution\x12\x0e\n\x06symbol\x18\x01 \x02(\t\x12\x0e\n\x06market\x18\x02 \x02(\t\x12\r\n\x05price\x18\x03 \x02(\x02\x12\x10\n\x08quantity\x18\x04 \x02(\x02\x12\x16\n\x0e\x65xecutionEpoch\x18\x05 \x02(\x03\x12\x13\n\x0bstateSymbol\x18\x06 \x02(\t')
)




_EXECUTION = _descriptor.Descriptor(
  name='execution',
  full_name='execution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='execution.symbol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='market', full_name='execution.market', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='execution.price', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='execution.quantity', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='executionEpoch', full_name='execution.executionEpoch', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stateSymbol', full_name='execution.stateSymbol', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['execution'] = _EXECUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

execution = _reflection.GeneratedProtocolMessageType('execution', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTION,
  __module__ = 'execution_pb2'
  # @@protoc_insertion_point(class_scope:execution)
  ))
_sym_db.RegisterMessage(execution)


# @@protoc_insertion_point(module_scope)
